/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("buildlogic.java-library-conventions")
}

dependencies {
    api(project(":utilities"))            // Import tool module
     testImplementation （libs.junit.api）    // Unified version management
     testRuntimeOnly(libs.junit.engine)
}